<?php

declare(strict_types=1);
// 全部路由名稱對應 OpenAPI operationId；route parity test 會驗證。
use App\Modules\Ai\Http\Controllers\AiController;
use App\Modules\Conversations\Http\Controllers\ContextController;
use App\Modules\Conversations\Http\Controllers\ConversationController;
use App\Modules\Conversations\Http\Controllers\PresenceController;
use App\Modules\Conversations\Http\Controllers\RealtimeController;
use App\Modules\Files\Http\Controllers\FileController;
use App\Modules\Identity\Http\Controllers\WidgetController;
use App\Modules\Integrations\Http\Controllers\HookController;
use App\Modules\Integrations\Http\Controllers\IntegrationController;
use App\Modules\Knowledge\Http\Controllers\KnowledgeController;
use App\Modules\Operations\Http\Controllers\CatalogController;
use App\Modules\Operations\Http\Controllers\ConfigurationController;
use App\Modules\Operations\Http\Controllers\OperationsController;
use Illuminate\Support\Facades\Route;

Route::post('widget/bootstrap', WidgetController::class)->middleware(['widget.inbox', 'throttle:widget-bootstrap', 'idempotent:encrypt'])->name('bootstrapWidget');
Route::post('widget/identity', WidgetController::class)->middleware(['widget.inbox', 'throttle:widget-identity', 'idempotent:encrypt'])->name('identifyVisitor');
Route::post('widget/token/refresh', WidgetController::class)->middleware([])->name('refreshVisitorToken');
Route::post('widget/logout', WidgetController::class)->middleware(['visitor.auth'])->name('logoutVisitor');
Route::get('widget/faqs', WidgetController::class)->middleware(['visitor.auth'])->name('listWidgetFaqs');
Route::put('widget/context', WidgetController::class)->middleware(['visitor.auth'])->name('updateWidgetContext');
Route::put('widget/attributes', WidgetController::class)->middleware(['visitor.auth'])->name('updateVisitorAttributes');
Route::get('widget/conversations', ConversationController::class)->middleware(['visitor.auth'])->name('listVisitorConversations');
Route::post('widget/conversations', ConversationController::class)->middleware(['visitor.auth', 'idempotent'])->name('createVisitorConversation');
Route::get('widget/conversations/{conversation_id}', ConversationController::class)->middleware(['visitor.auth'])->name('getVisitorConversation');
Route::get('widget/conversations/{conversation_id}/snapshot', ConversationController::class)->middleware(['visitor.auth'])->name('snapshotVisitorConversation');
Route::get('widget/conversations/{conversation_id}/messages', ConversationController::class)->middleware(['visitor.auth'])->name('listVisitorMessages');
Route::post('widget/conversations/{conversation_id}/messages', ConversationController::class)->middleware(['visitor.auth', 'idempotent'])->name('sendVisitorMessage');
Route::get('widget/conversations/{conversation_id}/events', ConversationController::class)->middleware(['visitor.auth'])->name('listVisitorEvents');
Route::put('widget/conversations/{conversation_id}/read', ConversationController::class)->middleware(['visitor.auth'])->name('markVisitorRead');
Route::post('widget/conversations/{conversation_id}/handoff', ConversationController::class)->middleware(['visitor.auth', 'idempotent'])->name('requestHuman');
Route::post('widget/conversations/{conversation_id}/resolve', ConversationController::class)->middleware(['visitor.auth', 'idempotent'])->name('visitorConfirmResolution');
Route::post('widget/conversations/{conversation_id}/csat', ConversationController::class)->middleware(['visitor.auth', 'idempotent'])->name('submitCsat');
Route::get('workspaces/{workspace_id}/conversations', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listStaffConversations');
Route::post('workspaces/{workspace_id}/conversations', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createStaffConversation');
Route::get('workspaces/{workspace_id}/conversations/{conversation_id}', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getStaffConversation');
Route::get('workspaces/{workspace_id}/conversations/{conversation_id}/snapshot', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('snapshotStaffConversation');
Route::get('workspaces/{workspace_id}/conversations/{conversation_id}/messages', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listStaffMessages');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/messages', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('sendStaffMessage');
Route::get('workspaces/{workspace_id}/conversations/{conversation_id}/events', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listStaffEvents');
Route::put('workspaces/{workspace_id}/conversations/{conversation_id}/read', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('markStaffRead');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/claim', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('staffClaim');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/assign', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('staffAssign');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/release', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('staffRelease');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/resolve', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('staffResolve');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/reopen', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('staffReopen');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/snooze', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('staffSnooze');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/resume-ai', ConversationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('staffResumeAi');
Route::post('workspaces/{workspace_id}/conversations/{conversation_id}/ai-drafts', AiController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createAiDraft');
Route::post('widget/broadcasting/auth', RealtimeController::class)->middleware(['visitor.auth'])->name('authorizeVisitorBroadcast');
Route::post('workspaces/{workspace_id}/broadcasting/auth', RealtimeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('authorizeStaffBroadcast');
Route::put('workspaces/{workspace_id}/presence', PresenceController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('updatePresence');
Route::post('widget/files/uploads', FileController::class)->middleware(['visitor.auth', 'idempotent'])->name('initiateVisitorUpload');
Route::post('widget/files/{file_id}/complete', FileController::class)->middleware(['visitor.auth', 'idempotent'])->name('completeVisitorUpload');
Route::get('widget/files/{file_id}', FileController::class)->middleware(['visitor.auth'])->name('getVisitorFile');
Route::get('widget/files/{file_id}/download', FileController::class)->middleware(['visitor.auth'])->name('downloadVisitorFile');
Route::post('workspaces/{workspace_id}/files/uploads', FileController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('initiateStaffUpload');
Route::post('workspaces/{workspace_id}/files/{file_id}/complete', FileController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('completeStaffUpload');
Route::get('workspaces/{workspace_id}/files/{file_id}', FileController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getStaffFile');
Route::get('workspaces/{workspace_id}/files/{file_id}/download', FileController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('downloadStaffFile');
Route::get('workspaces/{workspace_id}/knowledge-bases', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listKnowledgeBase');
Route::post('workspaces/{workspace_id}/knowledge-bases', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createKnowledgeBase');
Route::get('workspaces/{workspace_id}/knowledge-bases/{knowledge_base_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getKnowledgeBase');
Route::patch('workspaces/{workspace_id}/knowledge-bases/{knowledge_base_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateKnowledgeBase');
Route::get('workspaces/{workspace_id}/provider-connections', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listProviderConnection');
Route::post('workspaces/{workspace_id}/provider-connections', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createProviderConnection');
Route::get('workspaces/{workspace_id}/provider-connections/{provider_connection_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getProviderConnection');
Route::patch('workspaces/{workspace_id}/provider-connections/{provider_connection_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateProviderConnection');
Route::get('workspaces/{workspace_id}/ai-models', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listAiModel');
Route::post('workspaces/{workspace_id}/ai-models', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createAiModel');
Route::get('workspaces/{workspace_id}/ai-models/{ai_model_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getAiModel');
Route::patch('workspaces/{workspace_id}/ai-models/{ai_model_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateAiModel');
Route::get('workspaces/{workspace_id}/embedding-profiles', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listEmbeddingProfile');
Route::post('workspaces/{workspace_id}/embedding-profiles', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createEmbeddingProfile');
Route::get('workspaces/{workspace_id}/embedding-profiles/{embedding_profile_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getEmbeddingProfile');
Route::patch('workspaces/{workspace_id}/embedding-profiles/{embedding_profile_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateEmbeddingProfile');
Route::get('workspaces/{workspace_id}/ai-profiles', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listAiProfile');
Route::post('workspaces/{workspace_id}/ai-profiles', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createAiProfile');
Route::get('workspaces/{workspace_id}/ai-profiles/{ai_profile_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getAiProfile');
Route::patch('workspaces/{workspace_id}/ai-profiles/{ai_profile_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateAiProfile');
Route::get('workspaces/{workspace_id}/webhook-endpoints', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listWebhookEndpoint');
Route::post('workspaces/{workspace_id}/webhook-endpoints', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createWebhookEndpoint');
Route::get('workspaces/{workspace_id}/webhook-endpoints/{webhook_endpoint_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getWebhookEndpoint');
Route::patch('workspaces/{workspace_id}/webhook-endpoints/{webhook_endpoint_id}', ConfigurationController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateWebhookEndpoint');
Route::post('workspaces/{workspace_id}/provider-connections/{provider_connection_id}/probe', AiController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('probeProvider');
Route::get('workspaces/{workspace_id}/ai-runs/{ai_run_id}', AiController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getAiRun');
Route::post('workspaces/{workspace_id}/knowledge-documents', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createDocument');
Route::get('workspaces/{workspace_id}/knowledge-documents', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listDocuments');
Route::get('workspaces/{workspace_id}/knowledge-documents/{document_id}', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getDocument');
Route::post('workspaces/{workspace_id}/knowledge-documents/{document_id}/versions', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createDocumentVersion');
Route::get('workspaces/{workspace_id}/knowledge-documents/{document_id}/versions', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listDocumentVersions');
Route::get('workspaces/{workspace_id}/knowledge-versions/{version_id}', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getKnowledgeVersion');
Route::post('workspaces/{workspace_id}/knowledge-versions/{version_id}/index', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('indexKnowledgeVersion');
Route::post('workspaces/{workspace_id}/knowledge-versions/{version_id}/publish', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('publishKnowledgeVersion');
Route::post('workspaces/{workspace_id}/knowledge-documents/{document_id}/unpublish', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('unpublishDocument');
Route::post('workspaces/{workspace_id}/knowledge-search', KnowledgeController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('previewKnowledgeSearch');
Route::get('workspaces/{workspace_id}/api-clients', OperationsController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listApiClients');
Route::post('workspaces/{workspace_id}/api-clients', OperationsController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent:encrypt'])->name('createApiClient');
Route::post('workspaces/{workspace_id}/api-clients/{api_client_id}/revoke', OperationsController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('revokeApiClient');
Route::get('workspaces/{workspace_id}/webhook-deliveries', OperationsController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listWebhookDeliveries');
Route::post('workspaces/{workspace_id}/webhook-deliveries/{delivery_id}/retry', OperationsController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('retryWebhookDelivery');
Route::get('workspaces/{workspace_id}/reports/summary', OperationsController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getReportSummary');
Route::post('workspaces/{workspace_id}/exports', OperationsController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createExport');
Route::get('workspaces/{workspace_id}/async-tasks/{task_id}', OperationsController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getTask');
Route::post('integrations/contacts/upsert', IntegrationController::class)->middleware(['integration.auth', 'idempotent'])->name('upsertIntegrationContact');
Route::post('integrations/conversations', IntegrationController::class)->middleware(['integration.auth', 'idempotent'])->name('createIntegrationConversation');
Route::get('integrations/conversations/{conversation_id}', IntegrationController::class)->middleware(['integration.auth'])->name('getIntegrationConversation');
Route::post('integrations/conversations/{conversation_id}/messages', IntegrationController::class)->middleware(['integration.auth', 'idempotent'])->name('sendIntegrationInboundMessage');
Route::post('integrations/conversations/{conversation_id}/handoff', IntegrationController::class)->middleware(['integration.auth', 'idempotent'])->name('integrationHandoff');
Route::post('hooks/{connector_key}', HookController::class)->middleware([])->name('receiveGenericWebhook');

Route::get('workspaces/{workspace_id}/identity-issuers', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listIdentityIssuer');
Route::post('workspaces/{workspace_id}/identity-issuers', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createIdentityIssuer');
Route::get('workspaces/{workspace_id}/identity-issuers/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getIdentityIssuer');
Route::patch('workspaces/{workspace_id}/identity-issuers/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateIdentityIssuer');
Route::get('workspaces/{workspace_id}/channel-connectors', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listChannelConnector');
Route::post('workspaces/{workspace_id}/channel-connectors', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createChannelConnector');
Route::get('workspaces/{workspace_id}/channel-connectors/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getChannelConnector');
Route::patch('workspaces/{workspace_id}/channel-connectors/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateChannelConnector');
Route::get('workspaces/{workspace_id}/business-hours', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listBusinessHours');
Route::post('workspaces/{workspace_id}/business-hours', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createBusinessHours');
Route::get('workspaces/{workspace_id}/business-hours/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getBusinessHours');
Route::patch('workspaces/{workspace_id}/business-hours/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateBusinessHours');
Route::get('workspaces/{workspace_id}/macros', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listMacro');
Route::post('workspaces/{workspace_id}/macros', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createMacro');
Route::get('workspaces/{workspace_id}/macros/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getMacro');
Route::patch('workspaces/{workspace_id}/macros/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateMacro');
Route::get('workspaces/{workspace_id}/tags', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listTag');
Route::post('workspaces/{workspace_id}/tags', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createTag');
Route::get('workspaces/{workspace_id}/tags/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getTag');
Route::patch('workspaces/{workspace_id}/tags/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateTag');
Route::get('workspaces/{workspace_id}/resolution-reasons', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listResolutionReason');
Route::post('workspaces/{workspace_id}/resolution-reasons', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createResolutionReason');
Route::get('workspaces/{workspace_id}/resolution-reasons/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getResolutionReason');
Route::patch('workspaces/{workspace_id}/resolution-reasons/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateResolutionReason');
Route::get('workspaces/{workspace_id}/customer-attributes', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listCustomerAttribute');
Route::post('workspaces/{workspace_id}/customer-attributes', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('createCustomerAttribute');
Route::get('workspaces/{workspace_id}/customer-attributes/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getCustomerAttribute');
Route::patch('workspaces/{workspace_id}/customer-attributes/{resource_id}', CatalogController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('updateCustomerAttribute');

Route::get('workspaces/{workspace_id}/contacts/{contact_id}', ContextController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('getContactDetail');
Route::get('workspaces/{workspace_id}/conversations/{conversation_id}/tags', ContextController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff'])->name('listConversationTags');
Route::put('workspaces/{workspace_id}/conversations/{conversation_id}/tags', ContextController::class)->middleware(['staff', 'staff.auth', 'staff.workspace', 'throttle:staff', 'idempotent'])->name('replaceConversationTags');
